// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcRestauracja.Data;

#nullable disable

namespace MvcRestauracja.Migrations
{
    [DbContext(typeof(MvcRestauracjaContext))]
    [Migration("20240523142933_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("MvcRestauracja.Models.Danie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KlientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.ToTable("Danie");
                });

            modelBuilder.Entity("MvcRestauracja.Models.Kelner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataZatrudnienia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kelner");
                });

            modelBuilder.Entity("MvcRestauracja.Models.Klient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataZamowienia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StolikId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StolikId");

                    b.ToTable("Klient");
                });

            modelBuilder.Entity("MvcRestauracja.Models.Stolik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KelnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Nakrycie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KelnerId");

                    b.ToTable("Stolik");
                });

            modelBuilder.Entity("MvcRestauracja.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MvcRestauracja.Models.Danie", b =>
                {
                    b.HasOne("MvcRestauracja.Models.Klient", null)
                        .WithMany("Dania")
                        .HasForeignKey("KlientId");
                });

            modelBuilder.Entity("MvcRestauracja.Models.Klient", b =>
                {
                    b.HasOne("MvcRestauracja.Models.Stolik", "Stolik")
                        .WithMany()
                        .HasForeignKey("StolikId");

                    b.Navigation("Stolik");
                });

            modelBuilder.Entity("MvcRestauracja.Models.Stolik", b =>
                {
                    b.HasOne("MvcRestauracja.Models.Kelner", null)
                        .WithMany("Stoliki")
                        .HasForeignKey("KelnerId");
                });

            modelBuilder.Entity("MvcRestauracja.Models.Kelner", b =>
                {
                    b.Navigation("Stoliki");
                });

            modelBuilder.Entity("MvcRestauracja.Models.Klient", b =>
                {
                    b.Navigation("Dania");
                });
#pragma warning restore 612, 618
        }
    }
}
